# name: @name
# author: jishnurajendran
# upstream: https://github.com/rose-pine/hyprland/blob/main/dist/@id.conf
# @description

$base           = 0xff@base
$surface        = 0xff@surface
$overlay        = 0xff@overlay
$muted          = 0xff@muted
$subtle         = 0xff@subtle
$text           = 0xff@text
$love           = 0xff@love
$gold           = 0xff@gold
$rose           = 0xff@rose
$pine           = 0xff@pine
$foam           = 0xff@foam
$iris           = 0xff@iris
$highlightLow   = 0xff@highlightLow
$highlightMed   = 0xff@highlightMed
$highlightHigh  = 0xff@highlightHigh
